# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=1.0.0
maven_group=com.autofishing
archives_base_name=auto-fishing-mod
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.157.0+26.2
cloth_config_version=26.2.155+fabric
modmenu_version=20.0.1

# Toolchain: JDK 25 (required by Minecraft 26.2)
org.gradle.java.installations.paths=D:/IDE/Java/jdk-25.0.3
